version: '3.8'

services:
  surrealdb:
    build:
      context: ./server
      dockerfile: Dockerfile.surrealdb
    ports:
      - "8000:8000"
    volumes:
      - surrealdb_data:/data
    environment:
      - SURREAL_LOG=info
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - surrealdb
    environment:
      - SURREAL_DB_URL=ws://surrealdb:8000/rpc
      - SURREAL_DB_USER=root
      - SURREAL_DB_PASS=root
      - SURREAL_DB_NS=todolist
      - SURREAL_DB_DB=todos
    restart: unless-stopped

volumes:
  surrealdb_data:
    driver: local 