// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Category struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type CategoryInput struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

type Mutation struct {
}

type Query struct {
}

type Todo struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	Completed   bool       `json:"completed"`
	CategoryID  *string    `json:"categoryId,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	Location    *string    `json:"location,omitempty"`
	Priority    *int32     `json:"priority,omitempty"`
	Tags        []string   `json:"tags,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}

type TodoFilter struct {
	Completed  *bool      `json:"completed,omitempty"`
	CategoryID *string    `json:"categoryId,omitempty"`
	StartDate  *time.Time `json:"startDate,omitempty"`
	EndDate    *time.Time `json:"endDate,omitempty"`
	Priority   *int32     `json:"priority,omitempty"`
	Tags       []string   `json:"tags,omitempty"`
}

type TodoInput struct {
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	CategoryID  *string    `json:"categoryId,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	Location    *string    `json:"location,omitempty"`
	Priority    *int32     `json:"priority,omitempty"`
	Tags        []string   `json:"tags,omitempty"`
}

type TodoOutput struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	Completed   bool       `json:"completed"`
	Category    *Category  `json:"category,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	Location    *string    `json:"location,omitempty"`
	Priority    *int32     `json:"priority,omitempty"`
	Tags        []string   `json:"tags,omitempty"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}
