// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type Query struct {
}

type Todo struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	Completed   bool       `json:"completed"`
	Category    *string    `json:"category,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	Location    *string    `json:"location,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
}

type TodoFilter struct {
	Completed *bool      `json:"completed,omitempty"`
	Category  *string    `json:"category,omitempty"`
	StartDate *time.Time `json:"startDate,omitempty"`
	EndDate   *time.Time `json:"endDate,omitempty"`
}

type TodoInput struct {
	Title       string     `json:"title"`
	Description *string    `json:"description,omitempty"`
	Category    *string    `json:"category,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	Location    *string    `json:"location,omitempty"`
}
